services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${IMDB_BASE_IMAGE:-local/flagscale-agent-base-rewardkit:cu128-py312}

    image: local/flagscale-imdb-agent-eval:latest
    working_dir: /app
    command: ["bash", "-lc", "sleep infinity"]

    environment:
       HF_HOME: {HF cache Path} #添加HF cache 路径
      TRANSFORMERS_CACHE: {HF cache Path}/hub  #添加存储的模型文件缓存位置，降低重复下载
      TOKENIZERS_PARALLELISM: "false"
      HTTP_PROXY: http://用户名:密码@代理地址:80   #添加VPN
      HTTPS_PROXY: http://用户名:密码@代理地址:80  
      NO_PROXY: localhost,{本机 ip},{api 访问地址}   #添加容器访问哪些地址要跳过VPN，直接链接，例如：本机ip，模型推理请求的服务访问地址

    volumes:
      - {FlagScale-Agent Path}:/mnt/flagscale-agent-host:ro

      - {Imdb data Path}:/datasets/imdb:ro

      - {HF cache Path}:/root/.cache/huggingface:ro


    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: 
                - "${IMDB_GPU_DEVICE_ID}"
              capabilities: [gpu]
