services:
  main:
    build:
      context: .
      dockerfile: Dockerfile

    image: local/flagscale-pytorch-model-recovery:latest

    working_dir: /app

    command:
      - bash
      - -lc
      - sleep infinity

    environment:
      HF_HOME: /root/.cache/huggingface
      TRANSFORMERS_CACHE: /root/.cache/huggingface/hub
      TOKENIZERS_PARALLELISM: "false"
      HTTP_PROXY: http://flagcicd-yzli:A7fK9mQ2Zx4P@114.111.19.82:80
      HTTPS_PROXY: http://flagcicd-yzli:A7fK9mQ2Zx4P@114.111.19.82:80
      NO_PROXY: localhost,127.0.0.1,zyapi.xmsxb.com
    
    volumes:
      - {FlagScale-Agent Path}:/mnt/flagscale-agent-host:ro
